#5 描画関数の作成
human-osaka-game-2019/kageribi pull request #18
Opened 2019-10-28 12:31 UTC by chihiro390

DirectXの初期化とTextureを読み込む関数、描画するDraw関数作成しました。
レビューお願いします。

2019-10-29 08:55 UTC, taishi-matsumura requested changes

2019-10-29 08:55 UTC, taishi-matsumura commented on kageribi/DirectX.h
> +#define _DIRECTX_
`_` で始まるマクロ定数はやめときましょう。
[この記事](http://www.02.246.ne.jp/~torutk/cxx/file/includeguard.html) のシンボル名のセクションを読んでみて下さい。


他も同様です。

2019-10-29 08:55 UTC, taishi-matsumura commented on kageribi/DIrectX.cpp
> +
ここ、elseで括る必要ありますか？

2019-10-29 08:55 UTC, taishi-matsumura commented on kageribi/DIrectX.cpp
> +	vertex[3] = {};
これ、何がしたいの？

2019-11-01 08:42 UTC, chihiro390 commented on kageribi/DIrectX.cpp
> +
そうですね
書き直します。

2019-11-01 08:43 UTC, chihiro390 commented on kageribi/DIrectX.cpp
> +	vertex[3] = {};
すいません　書き忘れです
直します。

2019-11-01 08:44 UTC, chihiro390 commented on kageribi/DirectX.h
> +#define _DIRECTX_
分かりました。
読んで書き直します。

2019-11-01 13:12 UTC, taishi-matsumura commented on kageribi/DIrectX.cpp
> +
是正NGです。
elseで括るのをやめたのだから、インデントも修正して下さい。

2019-11-01 13:14 UTC, taishi-matsumura requested changes
再指摘しておきました

2019-11-01 13:14 UTC, taishi-matsumura commented on kageribi/DirectX.h
> +#endif // !_DIRECTX_
コメント修正漏れ

2019-11-01 13:14 UTC, taishi-matsumura commented on kageribi/Vec.h
> +#ifndef _VEC_
修正漏れ

2019-11-01 13:14 UTC, taishi-matsumura commented on kageribi/Vec.h
> +#endif // !_VEC_
修正漏れ

2019-11-01 13:29 UTC, chihiro390 commented on kageribi/DIrectX.cpp
> +
すいません　直します。

2019-11-02 11:55 UTC, chihiro390 commented on kageribi/Vec.h
> +#ifndef _VEC_
直しました。　e75cb30c192bb05bec819540186019fa324c8eae

2019-11-02 11:56 UTC, chihiro390 commented on kageribi/Vec.h
> +#ifndef _VEC_
直しました。　https://github.com/human-osaka-game-2019/kageribi/pull/18/commits/e75cb30c192bb05bec819540186019fa324c8eae

2019-11-02 16:12 UTC, taishi-matsumura approved these changes
@chihiro390 
是正確認しました。
コミット整理して下さい。

特に、
* includeガードのdefineの名前
* vertexの中身の書き忘れ
* elseの括ってた場所の修正
* インデントの修正
* コメントの修正漏れ
* VECファイルの修正漏れ

みたいなのはmasterの履歴に残すべきでは無いので、あたかも「元々そんなコードでしたよ？」みたいな履歴になるよう、コミットの分割・並べ替え・結合をしてみて下さい。
(指摘是正のコミットを最初から分割していれば手間省けたのに…)

2019-11-06 03:04 UTC, yky0126 approved these changes
Checking Source Code Done

2019-11-06 08:20 UTC, merged